import * as Icon from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export default function SolidIcon({ icon, iconColor, newClasses }) {
  const { [icon]: fontIcon } = {
    faArrowLeft: Icon.faArrowLeft,
    faArrowRight: Icon.faArrowRight,
    faArrowsUpDownLeftRight: Icon.faArrowsUpDownLeftRight,
    faBarcode: Icon.faBarcode,
    faBars: Icon.faBars,
    faBell: Icon.faBell,
    faBellConcierge: Icon.faBellConcierge,
    faBook: Icon.faBook,
    faBoxesStacked: Icon.faBoxesStacked,
    faBreadSlice: Icon.faBreadSlice,
    faBookOpen: Icon.faBookOpen,
    faBuilding: Icon.faBuilding,
    faBuildingShield: Icon.faBuildingShield,
    faBullseye: Icon.faBullseye,
    faBurger: Icon.faBurger,
    faCalculator: Icon.faCalculator,
    faCalendarDays: Icon.faCalendarDays,
    faCapsules: Icon.faCapsules,
    faCarSide: Icon.faCarSide,
    faChair: Icon.faChair,
    faChampagneGlasses: Icon.faChampagneGlasses,
    faChartColumn: Icon.faChartColumn,
    faChartLine: Icon.faChartLine,
    faChartPie: Icon.faChartPie,
    faChartSimple: Icon.faChartSimple,
    faCheck: Icon.faCheck,
    faChevronDown: Icon.faChevronDown,
    faChevronLeft: Icon.faChevronLeft,
    faChevronRight: Icon.faChevronRight,
    faCircleDot: Icon.faCircleDot,
    faCircleExclamation: Icon.faCircleExclamation,
    faCirclePlus: Icon.faCirclePlus,
    faClipboardList: Icon.faClipboardList,
    faClockRotateLeft: Icon.faClockRotateLeft,
    faCloudArrowUp: Icon.faCloudArrowUp,
    faCodeFork: Icon.faCodeFork,
    faCommentDollar: Icon.faCommentDollar,
    faComments: Icon.faComments,
    faComputer: Icon.faComputer,
    faCow: Icon.faCow,
    faDesktop: Icon.faDesktop,
    faDiagramProject: Icon.faDiagramProject,
    faDownload: Icon.faDownload,
    faDog: Icon.faDog,
    faDollarSign: Icon.faDollarSign,
    faFaceSmile: Icon.faFaceSmile,
    faFile: Icon.faFile,
    faFileCircleCheck: Icon.faFileCircleCheck,
    faFileContract: Icon.faFileContract,
    faFileInvoice: Icon.faFileInvoice,
    faFileInvoiceDollar: Icon.faFileInvoiceDollar,
    faFileExport: Icon.faFileExport,
    faFileLines: Icon.faFileLines,
    faFilePen: Icon.faFilePen,
    faFileWaveform: Icon.faFileWaveform,
    faFilterCircleDollar: Icon.faFilterCircleDollar,
    faFolderTree: Icon.faFolderTree,
    faGem: Icon.faGem,
    faHeadset: Icon.faHeadset,
    faHelmetSafety: Icon.faHelmetSafety,
    faHourglassHalf: Icon.faHourglassHalf,
    faIceCream: Icon.faIceCream,
    faJar: Icon.faJar,
    faLaptop: Icon.faLaptop,
    faLaptopMedical: Icon.faLaptopMedical,
    faLightbulb: Icon.faLightbulb,
    faListOl: Icon.faListOl,
    faLocationDot: Icon.faLocationDot,
    faLock: Icon.faLock,
    faMinus: Icon.faMinus,
    faMobileScreenButton: Icon.faMobileScreenButton,
    faMoneyBillTransfer: Icon.faMoneyBillTransfer,
    faMoneyBillTrendUp: Icon.faMoneyBillTrendUp,
    faMoneyBillWave: Icon.faMoneyBillWave,
    faMoneyCheckDollar: Icon.faMoneyCheckDollar,
    faMotorcycle: Icon.faMotorcycle,
    faPen: Icon.faPen,
    faPeopleLine: Icon.faPeopleLine,
    faPhone: Icon.faPhone,
    faTractor: Icon.faTractor,
    faTruck: Icon.faTruck,
    faRectangleList: Icon.faRectangleList,
    faRoute: Icon.faRoute,
    faScissors: Icon.faScissors,
    faSeedling: Icon.faSeedling,
    faSheetPlastic: Icon.faSheetPlastic,
    faShirt: Icon.faShirt,
    faSplotch: Icon.faSplotch,
    faStar: Icon.faStar,
    faStethoscope: Icon.faStethoscope,
    faStore: Icon.faStore,
    faSyringe: Icon.faSyringe,
    faUser: Icon.faUser,
    faUserCheck: Icon.faUserCheck,
    faUserGroup: Icon.faUserGroup,
    faUserNurse: Icon.faUserNurse,
    faUserTie: Icon.faUserTie,
    faXmark: Icon.faXmark,
    faWaterLadder: Icon.faWaterLadder
  };

  return (
    <FontAwesomeIcon
      className={`${newClasses && newClasses}`}
      icon={fontIcon}
      style={{ color: iconColor }}
    />
  );
}
